# Generated by Django 5.0.4 on 2025-04-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_dashboard', '0004_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category_name',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DummyCategoryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='General', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_dashboard.store')),
            ],
        ),
    ]
