# Generated by Django 5.0.4 on 2025-04-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_dashboard', '0005_inventory_category_name_dummycategoryinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummycategoryinventory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
