# Generated by Django 5.2 on 2025-04-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_type', models.CharField(max_length=1)),
                ('assortment', models.CharField(max_length=1)),
                ('competition_distance', models.IntegerField(blank=True, null=True)),
                ('competition_open_since_month', models.IntegerField(blank=True, null=True)),
                ('competition_open_since_year', models.IntegerField(blank=True, null=True)),
                ('promo2', models.BooleanField(default=False)),
                ('promo2_since_week', models.IntegerField(blank=True, null=True)),
                ('promo2_since_year', models.IntegerField(blank=True, null=True)),
                ('promo_interval', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('date', models.DateField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customers', models.IntegerField()),
                ('open', models.BooleanField()),
                ('promo', models.BooleanField()),
                ('state_holiday', models.CharField(max_length=1)),
                ('school_holiday', models.BooleanField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_dashboard.store')),
            ],
        ),
    ]
