# Generated by Django 5.0.4 on 2025-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_dashboard', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('date', models.DateField()),
                ('forecasted_sales', models.FloatField()),
            ],
            options={
                'unique_together': {('store_id', 'date')},
            },
        ),
    ]
